### ISSUE TITLE
Overall face for header line?

### ISSUE THREAD

**Issue by garyo** [joaotavora/breadcrumb#10]
Thanks for this lib! Very nice and simple. I'm using it with eglot and in org-mode.

It would be nice if there was a customizable var for the main face for the bc--header-line. (I think this is a different feature request from #9 which is asking for individual face controls for project and imenu faces, but I could be wrong.)
I could use advice to add a `:propertize` around the result but it would be nice to just set a face.

**Comment by joaotavora** [comment]
You don't need advice for doing this.

But go ahead and submit a pull request (ideally for this and #9 as well).  The closest the pull request is to the current coding convention, commit message etc, (which is very typical of Emacs projects), the easier it will be for me to merge it.

**Comment by joaotavora** [comment]
I've added lots of faces in the most recent version.  Have a look.
