### ISSUE TITLE
Unable to enable breadcrumb-local-mode

### ISSUE THREAD

**Issue by wanghaiqiangk** [joaotavora/breadcrumb#13]
Thanks for providing such good package. I'm also a eglot user.

When I tried to enable `breadcrumb-local-mode`, I met with such error: `(void-variable bc-local-mode)`

Environment:
OS: ubuntu 16.04
Emacs: 27.1

Procedures to reproduce:
1. `emacs -Q`
2. `M-;` and `(load "/path/to/breadcrumb")`

Debug info (`debug-on-error`):
```
Debugger entered--Lisp error: (void-variable bc-local-mode)
  breadcrumb-local-mode(toggle)
  funcall-interactively(breadcrumb-local-mode toggle)
  call-interactively(breadcrumb-local-mode record nil)
  command-execute(breadcrumb-local-mode record)
  execute-extended-command(nil "breadcrumb-local-mode" nil)
  funcall-interactively(execute-extended-command nil "breadcrumb-local-mode" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by joaotavora** [comment]
Sorry, requires Emacs 28 at least.

Maybe I'll make it Emacs-26/27 compatible later, it's not very hard...

**Comment by wanghaiqiangk** [comment]
Ah, I see. Time to upgrade my Emacs :)
