### ISSUE TITLE
propertize: Symbol’s function definition is void: project-name

### ISSUE THREAD

**Issue by dmitrym0** [joaotavora/breadcrumb#14]
Hello, I get `propertize: Symbol’s function definition is void: project-name` when running `breadcrumb-mode`.

Emacs 28.2 on macOS.

I `(load "breadcrumb.el)` and hit `M-x breadcrumb-mode`.

**Comment by joaotavora** [comment]
Get newer project.el via ELPA or use Emacs 29.

**Comment by dmitrym0** [comment]
What version of project is required?

**Comment by joaotavora** [comment]
get the most recent one.  If you want to help me make breadcrumb.el into a GNU ELPA pacakge -- which would record this version in the `breadcrumb.el` file and fix this problem for future users -- let me know.
