### ISSUE TITLE
File name black backgroud

### ISSUE THREAD

**Issue by arkhan** [joaotavora/breadcrumb#16]
Greetings, with the latest commits; I see that when I use Mini-Frame or the window goes to inactive, a black label is shown, instead of the file name.

I attach an image

After:
![image](https://github.com/joaotavora/breadcrumb/assets/3141865/a958387c-6de2-480f-870c-f25bc97e62f8)

Before:
![image](https://github.com/joaotavora/breadcrumb/assets/3141865/df37a2be-c69c-44ea-b5dc-00fdd0965848)

Thanks

**Comment by joaotavora** [comment]
There are a lot of new faces to customize, that should be `breadcrumb-project-leaf-face`.  As far as I can tell the default ones work fine with most of the themes I've tried.

**Comment by arkhan** [comment]
> There are a lot of new faces to customize, that should be `breadcrumb-project-leaf-face`. As far as I can tell the default ones work fine with most of the themes I've tried.

What variable should be modified to change this behavior?
