### ISSUE TITLE
Error during redisplay

### ISSUE THREAD

**Issue by xsteve** [joaotavora/breadcrumb#17]
I am not sure why breadcrumb mode does not work for some files.

Here is what I see when using it in a C file:
Error during redisplay: (eval (breadcrumb--header-line)) signaled (wrong-type-argument number-or-marker-p #<overlay from 1 to 33 in 1.c>) [3 times]

Entering a struct like this causes this problem:
```
struct mystruct {
    bool test;
};

```
Perhaps breadcrumb needs to strip off the overlays from the source file before putting data into the header-line.
The overlay range goes from the start of the struct definition to the end.
Sadly I don't know which package in my setup creates the overlay that causes the error.

**Comment by joaotavora** [comment]
I need a repro for this, otherwise guessing solutions is hard.  Can you trigger this with emacs -Q?

Or at least a backtrace.  Can you eval `(breadcrumb--header-line)` interactively with `M-:` ?

> Sadly I don't know which package in my setup creates the overlay that causes the error.

I don't have much better advice than to bisect your configuration.

**Comment by xsteve** [comment]
Here is a traceback:
`Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p #<overlay from 1 to 33 in 1.c>)
  <(34 #<overlay from 1 to 33 in 1.c>)
  (if (< pos (car (aref breadcrumb--ipath-plain-cache 0))) nil (let ((res (breadcrumb--bisect breadcrumb--ipath-plain-cache pos :key #'car :from-end t))) (if (= 0 res) nil (reverse (cdr (elt breadcrumb--ipath-plain-cache (1- res)))))))
  (let (--cl-dfs--) (setq --cl-dfs-- #'(lambda (n &optional ipath siblings) (progn (setq ipath (cons (car n) ipath)) (if (consp (cdr n)) (mapc #'... (cdr n)) (put-text-property 0 1 'breadcrumb-siblings (cdr siblings) (car ipath)) (setq breadcrumb--ipath-plain-cache (vconcat breadcrumb--ipath-plain-cache ...)))))) (if breadcrumb--ipath-plain-cache nil (mapc #'(lambda (i) (funcall --cl-dfs-- i nil index-alist)) index-alist) (setq breadcrumb--ipath-plain-cache (cl-sort breadcrumb--ipath-plain-cache #'< :key #'car))) (if (< pos (car (aref breadcrumb--ipath-plain-cache 0))) nil (let ((res (breadcrumb--bisect breadcrumb--ipath-plain-cache pos :key #'car :from-end t))) (if (= 0 res) nil (reverse (cdr (elt breadcrumb--ipath-plain-cache (1- res))))))))
  breadcrumb--ipath-plain((("mystruct{}" (#("*definition*" 0 1 (breadcrumb-siblings ((... . #<overlay from 20 to 30 in 1.c>)))) . #<overlay from 1 to 33 in 1.c>) (#("test" 0 1 (breadcrumb-siblings #4)) . #<overlay from 20 to 30 in 1.c>))) 34)
  (if (get-text-property 0 'breadcrumb-region (car (car index-alist))) (breadcrumb--ipath-rich index-alist pos) (breadcrumb--ipath-plain index-alist pos))
  breadcrumb-ipath((("mystruct{}" (#("*definition*" 0 1 (breadcrumb-siblings ((... . #<overlay from 20 to 30 in 1.c>)))) . #<overlay from 1 to 33 in 1.c>) (#("test" 0 1 (breadcrumb-siblings #4)) . #<overlay from 20 to 30 in 1.c>))) 34)
  (let* ((--cl-var-- (breadcrumb-ipath alist (point))) (more nil) (p nil) (--cl-var-- nil)) (while (consp --cl-var--) (progn (setq more --cl-var--) (setq p (car-safe (prog1 more (setq more (cdr more)))))) (setq --cl-var-- (cons (breadcrumb--format-ipath-node p more) --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--))
  (breadcrumb--summarize (let* ((--cl-var-- (breadcrumb-ipath alist (point))) (more nil) (p nil) (--cl-var-- nil)) (while (consp --cl-var--) (progn (setq more --cl-var--) (setq p (car-safe (prog1 more (setq more ...))))) (setq --cl-var-- (cons (breadcrumb--format-ipath-node p more) --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (breadcrumb--length breadcrumb-imenu-max-length) (propertize breadcrumb-imenu-crumb-separator 'face 'breadcrumb-face))
  (progn (breadcrumb--summarize (let* ((--cl-var-- (breadcrumb-ipath alist (point))) (more nil) (p nil) (--cl-var-- nil)) (while (consp --cl-var--) (progn (setq more --cl-var--) (setq p (car-safe (prog1 more ...)))) (setq --cl-var-- (cons (breadcrumb--format-ipath-node p more) --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (breadcrumb--length breadcrumb-imenu-max-length) (propertize breadcrumb-imenu-crumb-separator 'face 'breadcrumb-face)))
  (if (cl-some #'identity alist) (progn (breadcrumb--summarize (let* ((--cl-var-- (breadcrumb-ipath alist (point))) (more nil) (p nil) (--cl-var-- nil)) (while (consp --cl-var--) (progn (setq more --cl-var--) (setq p (car-safe ...))) (setq --cl-var-- (cons (breadcrumb--format-ipath-node p more) --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (breadcrumb--length breadcrumb-imenu-max-length) (propertize breadcrumb-imenu-crumb-separator 'face 'breadcrumb-face))))
  (if alist (if (cl-some #'identity alist) (progn (breadcrumb--summarize (let* ((--cl-var-- (breadcrumb-ipath alist ...)) (more nil) (p nil) (--cl-var-- nil)) (while (consp --cl-var--) (progn (setq more --cl-var--) (setq p ...)) (setq --cl-var-- (cons ... --cl-var--)) (setq --cl-var-- (cdr --cl-var--))) (nreverse --cl-var--)) (breadcrumb--length breadcrumb-imenu-max-length) (propertize breadcrumb-imenu-crumb-separator 'face 'breadcrumb-face)))) nil)
  (let* ((alist (and t (breadcrumb--ipath-alist)))) (if alist (if (cl-some #'identity alist) (progn (breadcrumb--summarize (let* ((--cl-var-- ...) (more nil) (p nil) (--cl-var-- nil)) (while (consp --cl-var--) (progn ... ...) (setq --cl-var-- ...) (setq --cl-var-- ...)) (nreverse --cl-var--)) (breadcrumb--length breadcrumb-imenu-max-length) (propertize breadcrumb-imenu-crumb-separator 'face 'breadcrumb-face)))) nil))
  breadcrumb-imenu-crumbs()
  eval((breadcrumb-imenu-crumbs) t)
`
The problem happens when doing M-: (breadcrumb-imenu-crumbs)

**Comment by xsteve** [comment]
And here is the content of breadcrumb--ipath-plain-cache:
`[(#<overlay from 1 to 33 in 1.c> #("*definition*" 0 1 (breadcrumb-siblings ...)) "mystruct{}") (#<overlay from 20 to 30 in 1.c> #("test" 0 1 (breadcrumb-siblings ...)) "mystruct{}")]
`

**Comment by joaotavora** [comment]
Can you tell me if this patch works?
```diff
diff --git a/breadcrumb.el b/breadcrumb.el
index 4bc731a..1b90e18 100644
--- a/breadcrumb.el
+++ b/breadcrumb.el
@@ -196,7 +196,15 @@ These structures don't have a `breadcrumb-region' property on."
                   (put-text-property 0 1 'breadcrumb-siblings (cdr siblings) (car ipath))
                   (setq bc--ipath-plain-cache
                         (vconcat bc--ipath-plain-cache
-                                 `[,(cons (cdr n) ipath)])))))
+                                 `[,(cons
+                                     ;; See github#17 and docstring of
+                                     ;; `imenu--index-alist' for the
+                                     ;; "overlay" edge case.
+                                     (cl-etypecase (cdr n)
+                                       (number (cdr n))
+                                       (marker (cdr n))
+                                       (overlay (overlay-start (cdr n))))
+                                     ipath)])))))
     (unless bc--ipath-plain-cache
       (mapc (lambda (i) (dfs i nil index-alist)) index-alist)
       (setq bc--ipath-plain-cache (cl-sort bc--ipath-plain-cache #'< :key #'car)))
```

**Comment by xsteve** [comment]
Yes - this patch fixes my observed problem :-)

**Comment by joaotavora** [comment]
OK, you must probably be using semantic from CEDET.  Can you confirm it also works if you turn it off in your setup?  I'll either push this patch or present something else.

**Comment by xsteve** [comment]
Exactly, I use semantic-mode from cedet. Turning semantic mode off has the effect that numbers are used instead of overlays in breadcrumb--ipath-plain-cache.
breadcrumbs are shown with and without semantic mode active in my setup (when using your proposed patch).

**Comment by joaotavora** [comment]
Can you paste the value of the variable `imenu--index-alist` in that simple `.c` file?  Then please do the same for a slightly more complex `.cpp` file, such as:

```
namespace foo {
class bar {
  int baz () {}
};
}
```

**Comment by xsteve** [comment]
Here is `imenu--index-alist` for the simple struct definition:
`(("mystruct{}" (#("*definition*" 0 1 ...) . #<overlay from 1 to 33 in 1.c>) (#("test" 0 1 ...) . #<overlay from 20 to 30 in 1.c>)))`

And here is its content for your namespace/class example:
`(("foo{}" ("bar{}" (#("*definition*" 0 1 ...) . #<overlay from 17 to 46 in 2.c>) (#("baz()" 0 1 ...) . #<overlay from 29 to 42 in 2.c>)) (#("*definition*" 0 1 ...) . #<overlay from 1 to 48 in 2.c>)))`

**Comment by joaotavora** [comment]
OK. Thanks, that answers my question although you seem to have used a `c` file for the second example, even though it is a C++ code sample. 

For some reason I can't see these same values in my machine, but then I don't use semantic at all.

With the patch that I gave you, does breadcrumb do anything useful when enabled in these buffers?

**Comment by xsteve** [comment]
I saved your code to 2.cpp -> `imenu--index-alist` gets the same values.
Your proposed patch shows useful information in these buffers now. Before the header line was empty due to the evaluation error.
