### ISSUE TITLE
This package has the same name as another Emacs package on MELPA

### ISSUE THREAD

**Issue by LemonBreezes** [joaotavora/breadcrumb#2]
Having trouble installing this package in Doom Emacs with 
```elisp
(package! breadcrumb :recipe (:host github :repo "joaotavora/breadcrumb"))
```
because `breadcrumb` gets pulled in from `emacsmirror` instead. Not sure if there's another way to install this with Doom Emacs and have it be auto-updated.

**Comment by RuijieYu** [comment]
Can you use `package-vc-install` in doom?  That's how I installed this package on vanilla Emacs.

**Comment by joaotavora** [comment]
Why this subject line??? "This package has the same name as another Emacs package on MELPA"  I could find it.

**Comment by joaotavora** [comment]
This software is very new and will be packaged soon, probably as a ELPA package.  In the meantime, this is a problem for Doom Emacs to handle.

After googling, I did find this Emacs related "breadcrumb" project, which hasn't been updated in 15 years: https://breadcrumbemacs.sourceforge.net/project.html

It's _not_ an ELPA or MELPA package as far as I can see.  I don't think it's a strong enough reason to change this project's name.
