### ISSUE TITLE
Incorrectly shortening project directory name

### ISSUE THREAD

**Issue by roife** [joaotavora/breadcrumb#20]
When working within projects named like `a.b` (such as `xxx.github.io`), `breadcrumb-project-crumbs` shortens names to `a`, which incorrectly interpreting `.b` as an extension.

However, since this is the name of a directory, this should not occur.

**Comment by joaotavora** [comment]
OK, I see you have a fix.  In that case submit as a PR, but please follow the commit message style of all the other commit messages.
