### ISSUE TITLE
Issues with folded org headings support

### ISSUE THREAD

**Issue by roife** [joaotavora/breadcrumb#22]
I have an org file with some headings folded. When I use the breadcrumb in this org file with collapsed headings, it triggers the following error.

```
Error during redisplay: (eval (+mode-line-normal)) signaled (error "Marker does not point anywhere")
```

Here's an example `org` file:

```org
* a

** aa

aa

** ab

ab
```

When fold all the second level headings, it's shown as:

```org
* a

** aa
** ab
```

After typing anything, the error mentioned above is triggered.

Then problem raised from the function `breadcrumb--ipath-plain`. `breadcrumb--ipath-plain` will compute `breadcrumb--ipath-plain-cache`, which turns out to be 

```
[(#<marker in no buffer> aa a) (#<marker in no buffer> ab a)]
```

I guess `#<marker in no buffer>` caused the error.

**Comment by joaotavora** [comment]
I can't reproduce this with latest Emacs master.  Perhaps you need to provide an Emacs -Q recipe that I can try?

**Comment by roife** [comment]
I start Emacs with the -q flag, install the "breadcrumb" package, and evaluate the configuration for as shown below to enable auto-rescanning for `imenu`:

```lisp
(use-package imenu
  :hook ((prog-mode conf-mode yaml-mode markdown-mode org-mode) . imenu-add-menubar-index)
  :config
  (setq imenu-auto-rescan t))
```

Afterward, I open an Org file, which contains the content mentioned earlier, and activate breadcrumb-local-mode. Then, I press the TAB key on the two second-level headlines (i.e., `** aa` and `** ab`). The file is folded as follows:

```lisp
* a

** aa
** ab
```

At this point, the breadcrumb works correctly because it caches `breadcrumb--ipath-plain-cache`. However, if I enter anything that triggers the recalculation of `breadcrumb--ipath-plain-cache`, the folded headlines will cause the error to occur.

Furthermore, it seems that after a certain period of time, the cache appears to return to its normal functioning.

**Comment by joaotavora** [comment]
Easiest fix is no remove `imenu-auto-rescan`. Seems useless with breadcrumb anyway.  But I'll see what can be done

**Comment by joaotavora** [comment]
Fixed.

But `imenu-auto-rescan` is a dreadful idea for Org anyway.  It's super slow and kicks in way more than it should.
