### ISSUE TITLE
Reducing expensive calculation of project root

### ISSUE THREAD

**Issue by alastairdb** [joaotavora/breadcrumb#29]
I was looking at the some of the Elisp standard libraries on a nix-based installation of Emacs. These lie under the `/nix/store/` directory which may have tens or hundreds of thousands of entries. I think this must cause calculation of the project root to be very expensive. In any event, scrolling with the mouse while in breadcrumb mode is unusable. Caching the return value of  `bc--project-crumbs-1` results in the usual smooth scrolling experience.

**Comment by joaotavora** [comment]
No benchmarks, no issue :-)  Could be a dup of https://github.com/joaotavora/breadcrumb/issues/18

**Comment by alastairdb** [comment]
Following the profile report in #18:
``` sh
> emacs -Q -l breadcrumb.el -f breadcrumb-mode /nix/store/wq7b9287kw2403mk52qllcml6jqz8rbk-emacs-gtk3-29.1/share/emacs/29.1/lisp/jka-compr.el.gz -f profiler-start
```
```
> ls -1 /nix/store | wc -l
67284

```
```
        7546  94% - command-execute
        7488  93%  - funcall-interactively
        7475  93%   - mwheel-scroll
        7419  92%    - scroll-up
        7419  92%     - eval
        7419  92%      - breadcrumb--header-line
        7419  92%       - let
        7419  92%        - cl-remove-if
        7419  92%         - mapcar
        7419  92%          - funcall
        7415  92%           - breadcrumb-project-crumbs
        7415  92%            - breadcrumb--summarize
        7411  92%             - if
        7411  92%              - breadcrumb--project-crumbs-1
        7411  92%               - catch
        7411  92%                - let*
        7391  92%                 - project-current
        7391  92%                  - project--find-in-directory
        7391  92%                   - project-try-vc
        7347  91%                    - locate-dominating-file
        7347  91%                       #<compiled 0x15c08eb5e7da5c67>
          44   0%                    + project--value-in-dir
          16   0%                 + while
           4   0%             + let
           4   0%           + breadcrumb-imenu-crumbs
           4   0%      mouse-wheel--get-scroll-window
           4   0%    - run-with-timer
           4   0%       run-at-time
          13   0%   - execute-extended-command
          13   0%    - command-execute
          13   0%       funcall-interactively
          58   0%  + byte-code
         410   5% - ...
         410   5%    Automatic GC
          31   0% + normal-top-level
          24   0% + timer-event-handler
           7   0% + jit-lock-function
```
I use straight in my init file and thus have a version of `project` from [https://github.com/emacs-straight/project](https://github.com/emacs-straight/project). I am using the latest version from that location and I don't see any obvious way to cache the call to `project-current` from within `project` itself

**Comment by joaotavora** [comment]
Just comment in #18.  This is most likely a dup of that issue.  You haven't said which Emacs versino or which project.el version you are using, you need be make sure of running the latest version.  I don't know straight stuff sorry, and I'm not even much into Emacs dev itself lately.  Just comment in #18, and maybe ping project.el maintainer if you can't find the solution there.  Thanks.
