### ISSUE TITLE
Performance of breadcrumb-mode in files with many nodes

### ISSUE THREAD

**Issue by the42** [joaotavora/breadcrumb#33]
When opening file types, where many nodes get assigned from the underlying mechanism (it's imenu and project.el?), the performance degrades rather badly.

I noticed this when switching from `js-json-mode` to `json-ts-mode` where the introspective capabilities of treeesitter populate many nodes to imenu. A file of 380kB, 18000 lines takes on my moderately performant computer about 10 seconds with `breadcrumb-mode` enabled, until Emacs becomes responsive again. If I remove breadcrumb-mode from autoload, the files opens about 10 times faster.

I assume this behaviour is not tied to json-ts-mode alone but to every mode, which operates on large files and where the files nature lends to the creation of many nodes, like yaml-ts-mode, xml-modes?

**Comment by joaotavora** [comment]
Like i've said in other similar issues, reproducible measurements or it didn't happen.  Give the file you use, the emacs version, the emacs invocation, blablabla, use `M-x profiler-start`, and then I will reopen.
