### ISSUE TITLE
Suggestion: Better Breadcrumb for Org Mode

### ISSUE THREAD

**Issue by whhone** [joaotavora/breadcrumb#35]
**Problem**: 'breadcrumb-imenu-crumbs changes the face (style) of the org heading.

**Suggestion**: Preserve the face (style) of org heading in breadcrumb.

Here is the idea (there is probably better solution)
```elisp
(defun breadcrumb-org-crumbs ()
  "Get the chain from the top level heading down to current heading."
  (org-format-outline-path (org-get-outline-path t)
                           (1- (frame-width))
                           nil
                           " > "))

(defun breadcrumb--header-line ()
  "Helper for `breadcrumb-headerline-mode'."
  (let* ((imenu-crumbs (if (eq major-mode 'org-mode)
                           'breadcrumb-org-crumbs
                         'breadcrumb-imenu-crumbs))
         (x (cl-remove-if
             #'seq-empty-p (mapcar #'funcall
                                   `(breadcrumb-project-crumbs ,imenu-crumbs)))))
    (mapconcat #'identity x (propertize " : " 'face 'bc-face))))
```

Proposed UI (Left) and Current UI (Right)

![breadcrumb](https://github.com/joaotavora/breadcrumb/assets/1200104/8fcc6c00-6e50-42bf-b822-ff1a2f40bf34)

**Comment by joaotavora** [comment]
breadcrumb is supposed to be major-mode agnostic.  This means it should know nothing about other major modes, org-mode, emacs-lisp-mode, c++-mode, thingamabob-mode, etc.  So while I agree your suggestion looks better, you should integrate it in your configuration.

So your solution (or something similar) is what it'll have to be unless you can somehow convince the org-mode developers to add breadcrumb-specific (or somehow agreed-upon) "cookies" to their imenu output.  Then `breadcrumb.el` will read these cookies and propertize the output accordingly.

**Comment by whhone** [comment]
I see. Thanks for the explanation!
