### ISSUE TITLE
breadcrumb performance issues--I now cache project-current, project-root, file-relative-name

### ISSUE THREAD

**Issue by shipmints** [joaotavora/breadcrumb#38]
Greetings and thank you for this package. I love its simplicity (and thanks for eglot a much richer ecosystem that I use).

I have noticed through profiling (and reading the code), that ```project-current```, ```project-root```, and ```file-relative-name``` dominate. None of these things can change once the buffer is established, so I've cached (memoized) them through some advice trickery and ```breadcrumb``` performs much better. These could be cached as buffer locals within ```breadcrumb``` natively or otherwise allow users to provide their own functions (and then cache on their own but that means lots of users repeating the same work).

I could look at patches but I'm not clear on the direction of the package or what approach you'd prefer or even if you agree that constantly calling functions whose results never change is acceptable.

Thank you.

**Comment by dgutov** [comment]
There was a discussion in https://github.com/joaotavora/breadcrumb/issues/18.

You're welcome to post the advices you've used (to apparent success) and/or propose a change which does that.

But see https://github.com/joaotavora/breadcrumb/issues/18#issuecomment-1984096948 in particular.

**Comment by shipmints** [comment]
Thank you. I'll close #38 and I'll read through and contribute, as needed, in #18. I am on Emacs 29.3 with project 0.9.8 (and which I've also locally advised to perform better).
