### ISSUE TITLE
Bug: Clicking on breadcrumb doesn't switch to clicked window

### ISSUE THREAD

**Issue by mohkale** [joaotavora/breadcrumb#7]
Hi there, I noticed a small bug.

If I have a 2 window split. LHS containing some code with breadcrumb active. RHS containing something else and being the focused window. And I click on the breadcrumb on the LHS window then my point is moved in the existing RHS window instead of first switching focus to the LHS and then moving point.

**Comment by joaotavora** [comment]
Can you check if this fixed it?

**Comment by mohkale** [comment]
Yep. Fixed now :-).
