### ISSUE TITLE
different faces

### ISSUE THREAD

**Issue by dchinmay2** [joaotavora/breadcrumb#9]
Can the project.el part and imenu part have different faces (as they represent different things in most languages)

**Comment by LemonBreezes** [comment]
This would be great! Currently I'm using 
```lisp
(setq-default mode-line-format
                (cl-subst '(:eval (propertize (breadcrumb-project-crumbs)
                                              'face '(:inherit variable-pitch
                                                      :weight bold)))
                          'mode-line-buffer-identification
                          (default-value 'mode-line-format)))
```
but it would be great if I could just modify a face for performance reasons.

**Comment by joaotavora** [comment]
"performance reasons"?

**Comment by LemonBreezes** [comment]
> "performance reasons"?

I mean, the only practical difference between the code I wrote and having a dedicated face that you don't have to call propertize each time the modeline is updated.

**Comment by joaotavora** [comment]
Hmmm, but you understand it's being called anyway right? Are you worried between an extra propertize call in a million propertize's?  I don't think this is measurable

**Comment by joaotavora** [comment]
Supplying these extra faces is fine though, I just don't have time to implement it properly right now.

**Comment by joaotavora** [comment]
I added lots of faces in a recent commit.  Please have a look.

**Comment by dchinmay2** [comment]
Yes this is great thanks!
